//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkilerHastaliklarStaj.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitki
    {
        public bitki()
        {
            this.recete = new HashSet<recete>();
        }
    
        public int bitki_id { get; set; }
        public string bitki_tr { get; set; }
        public string bitki_latin { get; set; }
        public string bitki_fotograf { get; set; }
        public string bitki_detay { get; set; }
    
        public virtual ICollection<recete> recete { get; set; }
    }
}
