//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkilerHastaliklarStaj.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastalik
    {
        public hastalik()
        {
            this.recete = new HashSet<recete>();
        }
    
        public int hastalik_id { get; set; }
        public string hastalik_tr { get; set; }
        public string hastalik_latin { get; set; }
        public string hastalik_tanim { get; set; }
        public string hastalik_detay { get; set; }
    
        public virtual ICollection<recete> recete { get; set; }
    }
}
