//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkilerHastaliklarStaj.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullanici_id { get; set; }
        public string kullanici_adi { get; set; }
        public string kullanici_soyadi { get; set; }
        public string kullanici_mail { get; set; }
        public string kullanici_sifre { get; set; }
        public Nullable<int> kullanici_yoneticilik { get; set; }
    }
}
