//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitkilerHastaliklarStaj.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class recete
    {
        public int recete_id { get; set; }
        public int recete_hastalik_id { get; set; }
        public int recete_bitki_id { get; set; }
    
        public virtual bitki bitki { get; set; }
        public virtual hastalik hastalik { get; set; }
    }
}
